name: Testing on PRs to master branch

on:
  pull_request:
    branches:
      - master
    paths:
      - "**/*.cs"

jobs:
  unit_tests:
    name: Unit tests 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'
      - name: Launch tests
        run: dotnet test --nologo